name: release-announcements
# Automatic release toot and tweet anouncements
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bsky-post:
    runs-on: ubuntu-latest
    steps:
      - uses: zentered/bluesky-post-action@v0.0.1
        with:
          post: |
            Pipeline release! ${{ github.repository }} v${{ github.event.release.tag_name }} - ${{ github.event.release.name }}!

            Please see the changelog: ${{ github.event.release.html_url }}
        env:
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          #
